version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - sbt-install
            - sbt-deps-{{ checksum "build.sbt" }}
      - run: |
          if [ ! -f /usr/bin/sbt ]; then
            echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
            sudo apt-get update
            sudo apt-get install sbt
          fi
      - run: sbt sbtVersion
workflows:
  version: 2
  build_and_test:
    jobs:
    - build