version: 2
jobs:
  build:
    docker:
      - image: mtranter/sbt-protoc:1.2.8_2.12
      - image: mtranter/gcp-pubsub-emulator:latest
        environment:
          PUBSUB_PROJECT_ID: test-project
    working_directory: ~/fs2-pubsub
    steps:
      - checkout
      - restore_cache:
          keys:
            - ivy
      - run: sbt ";set Global / patchVersion := Some(\"$CIRCLE_BUILD_NUM\");it:test;publish"
      - save_cache:
          key: ivy
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
workflows:
  version: 2
  build_and_test:
    jobs:
    - build:
        context: release
